spring:
  application:
    name: child-be

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:child_db}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.show_sql: true
    open-in-view: false
    show-sql: true
  server:
    servlet:
      encoding:
        charset: UTF-8
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:ai@idai.vn}
    password: ${MAIL_PASSWORD:gsjyqiazydhtvjuy}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        options:
          model: ${OPENAI_MODEL}

oauth2:
  identity:
    client-id: ${CLIENT_ID:1}
    client-secret: ${CLIENT_SECRET:2}
    redirect-uri: ${REDIRECT_URI:3}