spring:
  application:
    name: child-be

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:child_db}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.show_sql: true
    open-in-view: false
    show-sql: true
  server:
    servlet:
      encoding:
        charset: UTF-8

oauth2:
  identity:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    redirect-uri: ${REDIRECT_URI}